# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b4b7c63a5fabd3e754a65ad873fa09bdfde8b0fe3566f798fe83c9b2ecaffb625b95ccbd44adaad8918def15bb15eabc327cacb348a92e3815c8d5ad9ac1de

test:
  secret_key_base: 33cac600f5cf5f57c6042c7f4b37b1d3db8bf46d4c9a852a15295fa5fc89d21a17608798853e0db66b5e419cb3719c0ea63f7971fbb41b8cd3646c70e5bd1c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
